server:
  port: 3500

spring:
  cloud:
    gateway:
      routes:
        #student service API
        - id: student-service
          uri: lb://student-service
          predicates:
            - Path= /api/student/**
        #filier service API
        - id: filier-service
          uri: lb://filier-service
          predicates:
            - Path= /api/filier/**
        #level service API
        - id: level-service
          uri: lb://level-service
          predicates:
            - Path= /api/level/**
        #modal service API
        - id: modal-servvice
          uri: lb://modal-service
          predicates:
            - Path= /api/modal/**
        #professor service API
        - id: professor-service
          uri: lb://professor-service
          predicates:
            - Path= /api/professor/**
logging:
  level:
    root: INFO
    org.springFramework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springFramework.cloud.gateway: TRACE


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1500/eureka/