server:
  port: 3500

spring:
  cloud:
    gateway:
      routes:
        #student service API
        - id: student-service
          uri: lb://student-service
          predicates:
            - Path= /api/student/**
        #filier service API
        - id: filier-service
          uri: lb://filier-service
          predicates:
            - Path= /api/filier/**

logging:
  level:
    root: INFO
    org.springFramework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springFramework.cloud.gateway: TRACE


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1500/eureka/