server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1500/eureka/


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/leveldb
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
          format_sql: true
    show-sql: true
