server:
  port: 7700

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1500/ereuka/


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/professorDB
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
          format_sql: true
    show-sql: true